FROM golang:1.24

WORKDIR /app

# Копируем go.mod и устанавливаем зависимости
COPY go.mod go.sum ./
RUN go mod download

# Копируем всё остальное — для dev удобно, чтобы volume заменял содержимое
COPY . .

RUN mkdir -p logs

EXPOSE 8081

# Установка dockerize (для ожидания readiness БД и Kafka)
RUN wget https://github.com/jwilder/dockerize/releases/download/v0.6.1/dockerize-linux-amd64-v0.6.1.tar.gz && \
    tar -C /usr/local/bin -xzvf dockerize-linux-amd64-v0.6.1.tar.gz && \
    rm dockerize-linux-amd64-v0.6.1.tar.gz

CMD ["dockerize", "-wait", "tcp://postgres:5432", "-wait", "tcp://kafka:9092", "-timeout", "30s", "go", "run", "./cmd/main.go"]
